Fix github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,24 +3,20 @@ name: main branch test
 on: [push, pull_request]
 
 jobs:
-  citest:
-    name: CI test
-    runs-on: 'ubuntu-latest'
-
+  setup:
+    env:
+      IGNORE_PATHS: factor/totp/extlib
+    runs-on: ubuntu-latest
     services:
       postgres:
-        image: postgres:10
+        image: postgres:9.6
         env:
           POSTGRES_USER: 'postgres'
           POSTGRES_HOST_AUTH_METHOD: 'trust'
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 3
+        # Health check to wait for postgres to start.
         ports:
           - 5432:5432
-
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
       mariadb:
         image: mariadb:10
         env:
@@ -28,47 +24,33 @@ jobs:
           MYSQL_ALLOW_EMPTY_PASSWORD: "true"
         ports:
           - 3306:3306
-        options: >-
-          --health-cmd="mysqladmin ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 3
+        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
     strategy:
       fail-fast: false
       matrix:
         include:
-          - { moodle-branch: 'MOODLE_311_STABLE', php: '7.3', node: '14.15', database: 'mariadb' }
-          - { moodle-branch: 'MOODLE_311_STABLE', php: '7.3', node: '14.15', database: 'pgsql' }
-          - { moodle-branch: 'MOODLE_311_STABLE', php: '7.4', node: '14.15', database: 'mariadb' }
-          - { moodle-branch: 'MOODLE_311_STABLE', php: '7.4', node: '14.15', database: 'pgsql' }
-          - { moodle-branch: 'MOODLE_311_STABLE', php: '8.0', node: '14.15', database: 'mariadb' }
-          - { moodle-branch: 'MOODLE_311_STABLE', php: '8.0', node: '14.15', database: 'pgsql' }
-          - { moodle-branch: 'master', php: '7.3', node: '14.15', database: 'mariadb' }
-          - { moodle-branch: 'master', php: '7.3', node: '14.15', database: 'pgsql' }
           - { moodle-branch: 'master', php: '7.4', node: '14.15', database: 'mariadb' }
           - { moodle-branch: 'master', php: '7.4', node: '14.15', database: 'pgsql' }
-          - { moodle-branch: 'master', php: '8.0', node: '14.15', database: 'mariadb' }
-          - { moodle-branch: 'master', php: '8.0', node: '14.15', database: 'pgsql' }
     steps:
       - name: Check out repository code
         uses: actions/checkout@v2
         with:
+          # Clone in plugin subdir, so we can setup CI in default directory.
           path: plugin
 
-      - name: Install node  ${{ matrix.node }}
+      - name: Install node
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node }}
 
-      - name: Setup PHP ${{ matrix.php }}
-        uses: shivammathur/setup-php@v2
+      - name: Setup PHP environment
+        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
         with:
           php-version: ${{ matrix.php }}
-          extensions: pgsql, mysqli, zip, gd, xmlrpc, soap
-          coverage: none
-          ini-values: max_input_vars=5000
+          extensions: mbstring, pgsql, mysqli, gd, zip
+          tools: phpunit
 
-      - name: Initialise moodle-plugin-ci
+      - name: Deploy moodle-plugin-ci
         run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
           # Add dirs to $PATH
@@ -76,22 +58,24 @@ jobs:
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           # PHPUnit depends on en_AU.UTF-8 locale
           sudo locale-gen en_AU.UTF-8
-      - name: Install Moodle
-        run: |
-          mkdir ~/.npm-global
-          export PATH=~/.npm-global/bin:$PATH
-          source ~/.profile
-          moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
+      - name: Install moodle-plugin-ci
+        # Need explicit IP to stop mysql client fail on attempt to use unix socket.
+        run: moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
         env:
           DB: ${{ matrix.database }}
+          # TODO: Omitted MOODLE_BRANCH results in regex failure, investigate.
           MOODLE_BRANCH: ${{ matrix.moodle-branch }}
 
       - name: Run phplint
-        if: ${{ always() }}
         run: moodle-plugin-ci phplint
 
+      - name: Run phpcpd
+        run: moodle-plugin-ci phpcpd || true
+
+      - name: Run phpmd
+        run: moodle-plugin-ci phpmd
+
       - name: Run codechecker
-        if: ${{ always() }}
         run: moodle-plugin-ci codechecker
 
       - name: Run validate
@@ -103,24 +87,17 @@ jobs:
         run: moodle-plugin-ci savepoints
 
       - name: Run mustache
-        continue-on-error: true # This step will show errors but will not fail. Seems a bit unreliable.
         if: ${{ always() }}
         run: moodle-plugin-ci mustache
+
+      - name: Run grunt
+        if: ${{ always() }}
+        run: moodle-plugin-ci grunt -t amd
+
+      - name: Run phpdoc
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpdoc
 
       - name: Run phpunit
         if: ${{ always() }}
         run: moodle-plugin-ci phpunit
-
-      - name: Run behat
-        if: ${{ always() }}
-        run: moodle-plugin-ci behat --profile chrome
-
-      - name: PHP Copy/Paste Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd
-
-      - name: PHP Mess Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpmd
